### PR TITLE
BUG Backport of https://github.com/silverstripe/silverstripe-framework/pull/4077

### PR DESCRIPTION
**Pull request by tractorcow**
Better support for versions of framework 3.1.12 and older

### CODE REVIEW

**Comment by sminnee** [comment]
Good call—this makes things more flexible and work without hassles.

I wonder if it's worth commenting that this won't be necessary if the site is using silverstripe/framework 3.1.13 or higher, so that we know we can delete this code in 18 months time when the blog module it 3.2+ only anyway? ;-)

**Comment by assertchris** [comment]
There are other areas of blog that just won't work without 3.1.13/3.1.x-dev. Merging tags/categories for instance...

**Comment by tractorcow** [comment]
It's fine if it gracefully degrades. In this case, the feature is unusable not simply degraded.

**Comment by assertchris** [comment]
Merging tags and categories doesn't degrade. It doesn't work without JS.

**Comment by tractorcow** [comment]
Oh, is there a way we could disable that option on other framework versions?

Also this discussion has nothing to do with this PR.

**Comment by assertchris** [comment]
It's slightly related. What I'm trying to say is that it doesn't make sense to backport features to make blog 2.0 run on 3.1.12 if blog 2.0 requires 3.1.13 in other places.

**Comment by tractorcow** [comment]
Which PR in framework is necessary for those features? was it https://github.com/silverstripe/silverstripe-framework/pull/4079?

If you install blog module on an older version of framework what functions do you get? I would say a better solution is to review each of these features and make sure they degrade well.

**Comment by assertchris** [comment]
We need to render a custom row for each record in `GridField`. That's how we get the origin parent from which we move children.

**Pull request merged**
