### PR TITLE
Config spam notifications

### PR DESCRIPTION
**Pull request by camfindlay**
Allows dev to set whether a notification gets sent out to author if the comment is spam.

### CODE REVIEW

**Comment by dhensby** [comment]
as this is a new feature it should really go against 2 branch

**Comment by dhensby** [comment]
I've changed the base branch and rebased the code for you

**Comment by dhensby** [comment]
we need to drop hhvm from our build suite.

codecov test is timing out constantly, which is annoying.

**Comment by camfindlay** [comment]
Cheers @dhensby I had a look at the 2 branch and it seemed to be way behind the 2.4 branch, is the intention to back port a bunch of stuff from 2.4 into 2 branch before any 2.5.x version ?

**Comment by dhensby** [comment]
I'll arrange a merge up to 2

**Comment by dhensby** [comment]
all merged up

**Comment by dhensby** [comment]
merged up

**Pull request merged**
