### PR TITLE
API Enable rename of widgets

### PR DESCRIPTION
**Pull request by tractorcow**
This allows you to edit the widget titles.

### CODE REVIEW

**Comment by assertchris** [comment]
Might just be my setup, but posts aren't showing after applying this branch.

**Comment by tractorcow** [comment]
You might need a dev/build?

**Comment by micmania1** [comment]
You can't use Title as a db field in a widget. It conflicts with the private static $title.

**Comment by tractorcow** [comment]
Well, it does work.... :) That's how the old widget worked.

I can rename the DB field though, no problem.

**Comment by tractorcow** [comment]
Ok, maybe this change should go into widgets module....

**Pull request closed without merging**
