### PR TITLE
Added templates to blog module

### PR DESCRIPTION
**Pull request by Makreig**
This new module doesn't have any default templates so i have added some.

### CODE REVIEW

**Comment by mlewis-everley** [comment]
Is scrutinisher setup correctly for the blog? It seems to be erroring on trying to find the lumberjack module?

**Comment by dhensby** [comment]
Looks like all the composer stuff is messed up

**Comment by tractorcow** [comment]
There is also an existing PR (awaiting fixing some feedback though) at https://github.com/silverstripe/silverstripe-blog/pull/144, but we can probably collaborate to make a good theme from both. :)

**Comment by tractorcow** [comment]
And yep travis-ci tests from the old repo haven't actually been migrated across properly.

**Comment by mlewis-everley** [comment]
Hmm, would it make more sense for the templates to be managed via a seperate pull request to migration tasks?

I am just thinking that if there are issues with the templates, it will slow down merging the migration tasks and vice versa?

**Comment by tractorcow** [comment]
Yeah I can do that.

**Comment by mlewis-everley** [comment]
So, shall we break out the templates from #144, merge with ours and update this pull request?

**Comment by tractorcow** [comment]
Good idea, although I won't have much time to work on this PR this week.

**Comment by mlewis-everley** [comment]
I created a new pull request and merged in this #144. The new request is #146. Not sure if that was the best way to go about this, but it should now have all the code in one place...

**Comment by tractorcow** [comment]
I've added to @mlewis-everley 's PR at https://github.com/silverstripe/silverstripe-blog/pull/148

**Comment by tractorcow** [comment]
Closed ith #148

**Pull request closed without merging**
