### PR TITLE
i18n for the titles in the ArchiveWidget

### PR DESCRIPTION
**Pull request by marcokernler**

### CODE REVIEW

**Comment by tractorcow** [comment]
Whitespace needs to be fixed please. :D Please use tabs for indentation.

**Comment by marcokernler** [comment]
Converted the spaces to tabs :)

**Comment by dhensby** [comment]
Please can you "fixup" the commits? 

```sh
git reset HEAD^
git commit --amend --no-edit
git push --force
```

**Comment by marcokernler** [comment]
I've executed your commands. So it's ok for now?

**Comment by dhensby** [comment]
Himm, oops, I left a flag off of the commit line

Git commit -a --amend --no-edit

So your white space fixes didn't come through. Sorry....

**Comment by marcokernler** [comment]
Are there any tasks left that should be done?

**Comment by tractorcow** [comment]
Just that one.

**Pull request merged**
