### PR TITLE
FIX Don't hardcode table name

### LINKED ISSUE #628: Cannot loop over Children in Menu when BlogPost table is renamed
related to #620 

There is a hardcoded reference to table "BlogPost" in `SilverStripe\Blog\Model\BlogFilter::stageChildren()` that breaks looping over Children (e.g. in navigation) when the table is renamed.

PR will follow.

## PRs
- https://github.com/silverstripe/silverstripe-blog/pull/629

### PR DESCRIPTION
**Pull request by wernerkrauss**
BlogFilter had some hardcoded references to BlogPost table; when you rename this table, e.g. to "News", some joins broke.

related: #619

## Issue
- #628

### CODE REVIEW

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Looks good

There's some broken travis tests, though this is related to it using an old .travis.yml file.  Could you please either:
a) rebase on top of `3`, or
b) rebase on top of `3.6` and retarget this PR at `3.6` (preferable, we can patch release this then)

**Comment by wernerkrauss** [comment]
Ping... I stumbled over that issue. Which branch should I rebase it to? Now Branch 4 for CMS5?

**Comment by emteknetnz** [comment]
4.1 for a patch release on CMS 5

**Comment by GuySartorelli** [comment]
I've rebased this against `4.2` and pushed without any changes.
Assuming CI goes green, I'll be happy to merge it.

**Pull request merged**
