### PR TITLE
Break out templates and expand

### PR DESCRIPTION
**Pull request by mlewis-everley**
I have merged the pull request #144, removed the migration tasks and legacy model classes and then merged in the code from @Makreig.

Not sure if this is the best way to do this?

### CODE REVIEW

**Comment by tractorcow** [comment]
Wow this is great work. I'm reviewing it now.

It's great to see other contributors working together on code. :)

**Comment by tractorcow** [comment]
I've added some fixes (as documented) and squashed at https://github.com/silverstripe/silverstripe-blog/pull/148 for review.

**Comment by mlewis-everley** [comment]
No probs, I think the blog module is the core module (outside of the cms) that we use the most, and is really in need of an upgrade, so happy to provide any help we can give :-)

**Comment by tractorcow** [comment]
Closed with #148

**Pull request closed without merging**
