### PR TITLE
UPDATE: change the links for readme badges

### PR DESCRIPTION
**Pull request by stevie-mayhew**

### CODE REVIEW

**Comment by micmania1** [comment]
The build status image is 404 :(

**Comment by stevie-mayhew** [comment]
Its never as simple as you want it to be is it :smile:

**Comment by micmania1** [comment]
I think it should be silverstripe/silverstripe-blog instead of silverstripe/blog

**Comment by stevie-mayhew** [comment]
Sweet, thats sorted @micmania1

**Comment by micmania1** [comment]
Thanks :+1:

**Pull request merged**
