### PR TITLE
Fix bad call to getminInnerWidth()

### PR DESCRIPTION
**Pull request by nimeso**
This is not a function :(

### CODE REVIEW

**Comment by tractorcow** [comment]
Actually, it is. If you check the entwine documentation http://hafriedlander.github.io/jquery.entwine/tutorial/step_05.html this is the standard way to access these properties.

The correct fix for the known issue is to adjust the capitalisation of the property, as it's meant to have a leading capital letter.

**Comment by nimeso** [comment]
@tractorcow thanks!

**Comment by dhensby** [comment]
So... Closing?

**Comment by tractorcow** [comment]
Right, thanks @dhensby :D

**Pull request closed without merging**
