### PR TITLE
Adjusted minimum stability flag to reflect dev-develop usage

### PR DESCRIPTION
**Pull request by assertchris**
Scrutinizer is having trouble, and I think this might help it along.

### CODE REVIEW

**Comment by assertchris** [comment]
Scrutinizer are having issues analysing framework. I'm closing this until I hear back from them about that.

**Comment by tractorcow** [comment]
@assertchris should we turn off inspection of external code? https://scrutinizer-ci.com/docs/configuration/filter

Maybe add /vendor/* to the exclusion list?

**Comment by assertchris** [comment]
Trouble is Scrutinizer won't be able to type check the code then.

**Comment by tractorcow** [comment]
Darn, well, scrutinizer doesn't seem to complain when being run on the framework itself.

https://scrutinizer-ci.com/g/silverstripe/silverstripe-framework/inspections/481a859c-dfb1-4b54-b2ee-d86f60168ecc/log

I'm going to re-open this PR to review the results again.

**Comment by tractorcow** [comment]
@assertchris any other information you can post here on the issue as you understand it would be helpful. :D

**Comment by assertchris** [comment]
Good idea. Well there are unstable dependencies, and the default minimum stability is "stable". That means, when `composer install|update` is run on this repository; the dependencies cannot be resolved. I suggested this change so that Travis and Scrutinizer would be able to run `composer install|update`.

**Comment by tractorcow** [comment]
We seem to be running a lot more tests on the modules than we are on core. For comparison:

framework: https://scrutinizer-ci.com/g/silverstripe/silverstripe-framework/inspections/481a859c-dfb1-4b54-b2ee-d86f60168ecc/log
blog: https://scrutinizer-ci.com/g/silverstripe/silverstripe-blog/inspections/18bf95a9-cf77-44c6-844d-36dec60a6ec4

**Comment by tractorcow** [comment]
And here is the config we are using for framework inspections.

```yaml
tools:
    php_cs_fixer: true
    php_code_sniffer:
        config:
            standard: PSR1
    php_mess_detector: true
    php_cpd: true
    php_analyzer:
        filter:
            excluded_paths: ["*/Tests/*"]
    sensiolabs_security_checker: true

checks:
    php:
        verify_argument_usable_as_reference: false
```

Plus the .scrutinizer.yml included in the repo

https://github.com/silverstripe/silverstripe-framework/blob/3.1/.scrutinizer.yml

I don't have access to the blog configuration.

**Comment by tractorcow** [comment]
I need to read through https://scrutinizer-ci.com/docs/configuration/best_practices and figure out what the current state is and what we should do to configure each module. :)

**Pull request merged**
