### PR TITLE
Update deps to use ^

### PR DESCRIPTION
**Pull request by camfindlay**
Better?

### CODE REVIEW

**Comment by tractorcow** [comment]
@camfindlay don't forget to create your pull requests from your fork. :)

**Comment by dhensby** [comment]
These two syntaxes resolve to exactly the same thing :/

**Comment by dhensby** [comment]
^ exactly :)

**Comment by dhensby** [comment]
Wait, what?

**Comment by dhensby** [comment]
Oh, coz of 0.X example? Well, yes, but that doesn't apply here.

**Comment by dhensby** [comment]
Machine learning has a long way to come.

**Comment by dhensby** [comment]
Yes, I'm talking about this example through where this is true: 

~3.1 is equivalent to >=3.1.0 <4.0.0
^3.1 is equivalent to >=3.1.0 <4.0.0

**Comment by dhensby** [comment]
I don't refute there is a difference. Just not in this context.

**Comment by dhensby** [comment]
No. I'm citing the example in this change :)

<3 4 bots

**Comment by dhensby** [comment]
>Yes there is. tagfield was ~1.0.0 

Shit. Out done by a robot

**Comment by dhensby** [comment]
You just floored me

**Comment by dhensby** [comment]
Who's that beauty?

**Comment by camfindlay** [comment]
@helpfulrobot 01000100 01101111 01101101 01101111 00100000 01100001 01110010 01101001 01100111 01100001 01110100 01101111 00100000 01001101 01110010 00101110 00100000 01001000 01100101 01101100 01110000 01100110 01110101 01101100 00100000 01010010 01101111 01100010 01101111 01110100 01101111

**Comment by dhensby** [comment]
Thanks indeed

**Comment by micmania1** [comment]
...and so the downfall of humanity begin.

**Pull request merged**
