### PR TITLE
MNT ESLint issues

### PR DESCRIPTION
**Pull request by sabina-talipova**
## Description
Turn on some of the ESLint.
## Parent issue
-  https://github.com/silverstripe/silverstripe-admin/issues/1433

### CODE REVIEW

**Comment by sabina-talipova** [comment]
Failed Behat tests are unrelated to changes that has been done.

**Review by emteknetnz — APPROVED** [review]

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Failing tests

**Comment by sabina-talipova** [comment]
Only one `indent` rule was applied in this file, which should not cause this problem. When I test it manually there is no problem.

**Review by emteknetnz — APPROVED** [review]

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Please change the commit and PR prefix from FIX to MNT

**Review by emteknetnz — APPROVED** [review]

**Pull request merged**
