### PR TITLE
New commit for PR - #489

### PR DESCRIPTION
**Pull request by MichaelJJames**
@robbieaverill

### CODE REVIEW

**Comment by robbieaverill** [comment]
This is just the dist file - are we missing the source change a well?

**Comment by MichaelJJames** [comment]
Updated

**Comment by robbieaverill** [comment]
Ok so this change looks alright on desktop but looks a bit off on smaller devices:

image
image
image
image

Might I suggest adding this as padding on the toggle composite field instead?

```css
#Form_EditForm_Summary_Holder {
  padding: 20px;
}
```

image
image
image
image

**Comment by robbieaverill** [comment]
I actually feel like this could be addressed in the CMS module instead. Regardless, feel free to reopen the PR if you'd like to revisit it again =) Thanks for contributing @MichaelJJames!

**Pull request closed without merging**
