### PR TITLE
fixed namespacing for widgets

### LINKED ISSUE #495: namespacing for widgets seems to be broken

### PR DESCRIPTION
**Pull request by korthjp17**
fixes #495

### CODE REVIEW

**Comment by robbieaverill** [comment]
Thanks for the fix. For context, the namespace was changed here: https://github.com/silverstripe/silverstripe-widgets/pull/163

**Comment by robbieaverill** [comment]
Looks like there's a failure in the unit tests (which could easily be a pre-existing issue). Would you be keen to try and fix it?

**Comment by korthjp17** [comment]
@mak001 is this something you can help me with?

**Comment by robbieaverill** [comment]
I've just had a quick look at the test failure, here's a couple of notes:

* The fixture that is failing to be loaded is being successfully loaded in [a different test](https://github.com/silverstripe/silverstripe-blog/blob/master/tests/Widgets/BlogArchiveWidgetTest.php#L40) from the draft stage
* The failure is when trying to load the fixtured widget from the live stage
* The failing test published the owner BlogPost recursively (which should publish the widgets too) before switching the stage

I think in https://github.com/silverstripe/silverstripe-widgets/pull/163 we implemented the ownership  API into the widgets module, which is probably causing this error. It looks as if the way widgets are associated to blog pages in this module needs to be updated, since it's more like a has_one from Widget to Blog/BlogPost rather than using the intermediary WidgetArea, which is where the ownership API is centered.

I think this will need a little more work to fix. For now this pull request is a good improvement, so I think we can merge it.

@dhensby do you agree?

**Comment by dhensby** [comment]
@robbieaverill yep, if the namespaces are wrong, lets merge that and worry about the tests separately.

**Comment by dhensby** [comment]
Though I'm not sure why widgetcontrollers are in the Model namespace ;)

**Comment by robbieaverill** [comment]
They don't _have_ to be, but [this logic](https://github.com/silverstripe/silverstripe-widgets/blob/master/src/Model/Widget.php#L247-L252) indicates that it makes more sense for them to live there for now

**Comment by dhensby** [comment]
@robbieaverill whoops - this caused a regression in the test suite which we didn't spot :(

**Comment by dhensby** [comment]
OK - maybe not this PR explicitly, maybe an upstream change - it looks like we aren't publishing a widget in the test when we need to.. PR incoming

**Pull request merged**
