### PR TITLE
API Deprecate widget classes

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-blog/issues/589

### CODE REVIEW

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
There's templates to delete too, e.g. `templates/WidgetHolder.ss`
There's also scss, docs, test files (e.g. `tests/behat/src/FeatureContext.php`), and config related to widgets that all need to be removed - and a mention in the readme.

**Comment by emteknetnz** [comment]
Have created 5.3.0 changelog PR - https://github.com/silverstripe/developer-docs/pull/567

Re templates etc - this is just the deprecation PR, not the removal PR, that happens in CMS 6

**Comment by GuySartorelli** [comment]
Oh yup sorry, got ahead of myself.

**Review by GuySartorelli — APPROVED** [review]
LGTM

**Pull request merged**
