### PR TITLE
ENHANCEMENT: Added code coverage and extra badges on the README

### PR DESCRIPTION
**Pull request by gordonbanderson**
Addition of code coverage upload to codecov.io and extra badges on the README file

An example can be found at https://github.com/gordonbanderson/silverstripe-blog/tree/coverage (note this branch has paths set for SilverStripe repos)

### CODE REVIEW

**Comment by tractorcow** [comment]
:D

**Comment by tractorcow** [comment]
Anything else I need to do to get the codecon icon working on the home page? It looks broken.

Is https://codecov.io/github/silverstripe/silverstripe-blog setup correctly?

**Comment by gordonbanderson** [comment]
Wait, do nothing, and things are fixed.... I've noticed some weird caching issues as GitHub uses URLs like of https://camo.githubusercontent.com/b3ec0f3508670b9eee337d0610de1d4ed7b7b9ee/68747470733a2f2f636f6465636f762e696f2f6769746875622f73696c7665727374726970652f73696c7665727374726970652d626c6f672f636f7665726167652e7376673f6272616e63683d6d6173746572 (the one you considered broken), so I suspect some caching on Github's part.

**Comment by tractorcow** [comment]
Ah, I just had to wait it out it seems. Nice.

**Comment by gordonbanderson** [comment]
..... and 8 hours later the Version Eye ones are not working :(


As an aside, interested in yours and other core developers thoughts on using CodeCov and badges.  A few people have gone 'whoooooaaaa, so. many. badges.' but I think they are useful, lots of green immediately means the owner cares.  Unless of course the viewer is red/green color blind ;)

Even is my selection of badges is not the definitive one it would be good to see consistency over SilverStripe core modules, which would set a benchmark for others to follow.  I've been fixing up and releasing some old modules of mine with regards to testing and continuous integration, I will publish the scripts I've used once I'm 100% happy with them.  They do the following, working on the assumption it's an older module:
* Add git attributes file
* Add editor config
* Add generic Travis file with correct module path variable set, this runs tests and adds code coverage
* Add badges to the README.md file
* Adds a BSD3 license if no license existing.
* Creates one test per method, with the implementation marked as skipped (i.e. a functional test suite but with zero coverage)
* Outputs a note as to how to add module to Scrutinizer and Travis with appropriate links and Github user/project names.


Of the SilverStripe projects I've added code coverage to so far figures are as follows coverage wise:
- Framework 35% https://codecov.io/github/gordonbanderson/silverstripe-framework?ref=f78d75159a3060a3b98e102982f262ef09156044
- Blog 57%
- Comments 54% (now 92% after my additions)

This suggests to me that more work is needed on the unit testing front.


What's the most appropriate way to discuss these issues with the SS community?  I was thinking create a generic issue under Framework on GitHub and then an email to the developers list.

**Comment by tractorcow** [comment]
If you aren't already, you should join in discussing these on the google groups for silverstripe-dev. https://groups.google.com/forum/#!forum/silverstripe-dev

Code coverage has been a sore point in our modules' CI for a long time now... and we are aching for a solution that works. Your implementation seems to be it!

**Comment by gordonbanderson** [comment]
Yip I'm on the list.  Looks like I have a long email to write :)

**Pull request merged**
