### PR TITLE
BUG Fix Type field conflict with core Widget field

### PR DESCRIPTION
**Pull request by tractorcow**
Type is used for the widget classname

### CODE REVIEW

**Comment by micmania1** [comment]
It needs a migration script for upgrading as other DO's have.

**Comment by tractorcow** [comment]
Yeah I'll include it... I'm working on a PR for widgets at the moment so I will update this at the same time.

**Comment by tractorcow** [comment]
I've update this as suggested.

I've also updated it to work nicely with widgets module, should https://github.com/silverstripe/silverstripe-widgets/pull/84 be merged.

**Comment by tractorcow** [comment]
Thanks. :)

**Pull request merged**
