### PR TITLE
FIX: augmentLoadLazyFields doesn't work with renamed tables

### PR DESCRIPTION
**Pull request by wernerkrauss**
On a project I renamed the table BlogPosts to News_Posts which led to a broken join clause.

### CODE REVIEW

**Review by kinglozzer — APPROVED** [review]

**Comment by dnsl48** [comment]
Hi! Thank you for the PR.

## merge checklist
 
* [ ] the target branch is [correct](https://docs.silverstripe.org/en/4/contributing/code/#picking-the-right-version)
* [x] all commits are relevant (e.g. no debugging and linting)
* [ ] the commit messages follow [the contribution guidelines](https://docs.silverstripe.org/en/4/contributing/code/#commit-messages)
* [x] the patch follows [the contribution guidelines](https://docs.silverstripe.org/en/4/contributing/code/)
* [ ] new features are covered with tests (back-end with unit tests, front-end with Behat)
* [ ] the relevant CMS documentation is updated; changelog for impactful changes
* [x] CI is green
* [x] at least one peer reviewer approved; no changes requested

**Review by dnsl48 — CHANGES_REQUESTED** [review]
The patch is looking good! Just need to address a couple items from the checklist

 - could you please retarget at the branch `3` instead of `master` so it makes it into the next MINOR release (`3.6`)
 - add a prefix "FIX" to the commit message

Everything else is looking good!

**Comment by wernerkrauss** [comment]
Done

**Review by dnsl48 — APPROVED** [review]

**Comment by dnsl48** [comment]
Thank you for the contribution!

**Pull request merged**
