### PR TITLE
Fix excerpt parsing

### PR DESCRIPTION
**Pull request by flashbackzoo**
Before:
blog-excerpt-before

After:
blog-excerpt-after

### CODE REVIEW

**Comment by flashbackzoo** [comment]
Fixes https://github.com/silverstripe/silverstripe-blog/pull/238

**Comment by tractorcow** [comment]
good job!

**Comment by assertchris** [comment]
It has a desirable effect, but doesn't fix the underlying problem. Keen to merge this and still deal with the other value getters...

**Comment by tractorcow** [comment]
The core issue is at https://github.com/silverstripe/silverstripe-framework/issues/1381

I think it should probably be fixed in a point release, since it should probably involve some level of api cleanup.

**Comment by tractorcow** [comment]
Really there's no point having both Summary and LimitWordCount that attempt to do the same thing.

**Pull request merged**
