### PR TITLE
Update composer constraints for tagfield

### PR DESCRIPTION
**Pull request by kinglozzer**
See #293

### CODE REVIEW

**Comment by SpiritLevel** [comment]
Can anyone tell me the time between a change getting merged here on github and that same change propagating to packagist ?

**Comment by stevie-mayhew** [comment]
@SpiritLevel its as soon as the tag is released, about 20 seconds usually

**Comment by SpiritLevel** [comment]
Thanks @stevie-mayhew...and the tag release time, I imagine, is far less predictable!  ;)

**Comment by stevie-mayhew** [comment]
@SpiritLevel - blog is usually pretty quickly

**Comment by SpiritLevel** [comment]
@stevie-mayhew   Thanks:)..Good to know. I have something small in framework in 3.2 branch but it doesn't appear in any of the 3.2.* tags yet...I guess the next tag release for 3.2 will be the stable one 3.2.0...is that right ?

**Comment by stevie-mayhew** [comment]
I'll have to leave that answer to a core contributer :)

**Comment by kinglozzer** [comment]
Ping @assertchris @micmania1 @tractorcow. Can someone merge this and tag a new release? Blog is currently as good as broken on 3.2 :(

**Comment by kinglozzer** [comment]
Now that’s what I call speed. Many thanks @assertchris!

**Comment by assertchris** [comment]
@kinglozzer you're welcome. Sorry it took so long to see this.

**Pull request merged**
